### ISSUE TITLE
SyntaxError in latest version of imaging.py

### ISSUE THREAD

**Issue by sebastian-luna-valero** [AMIGA-IAA/hcg-16#2]
Hi,

I am re-running the pipeline with the latest version of `imaging.py` and it throws the error below.

@jonesmg could you please have a look?

Best regards,
Sebastian

```
=========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
=========================================

IPython: /data IPython 5.1.0 -- An enhanced Interactive Python.

CASA 5.1.2-4   -- Common Astronomy Software Applications

--> CrashReporter initialized.
Traceback (most recent call last):
  File "/opt/casalite-4.7.0.1/lib/python2.7/init_welcome.py", line 24, in <module>
    execfile(__candidates[0])
  File "hcg-16-master/casa/imaging.py", line 82
    (imagename="HCG16_CD_rob2_MS_cleanmask.image",moments=[0],axis="spectral",region="",box="",chans="0",stokes="",mask="",includepix=[0.00108, 1000000],excludepix=-1,outfile="HCG16_CD_rob2_MS_cleanmask.mom0",stretch=False)
              ^
SyntaxError: invalid syntax
```

**Comment by jonesmg** [comment]
There were some blank spaces hidden in some line breaks in these new commands. I think I have found and removed them all in commit 8d91ee0.

**Comment by sebastian-luna-valero** [comment]
Many thanks, that fixed it!
